//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Game_Store_App.Database
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Products
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public byte MinPlayerAmount { get; set; }
        public byte MaxPlayerAmount { get; set; }
        public string Description { get; set; }
        public decimal NumForBuy { get; set; }
        public Nullable<decimal> NumForRent { get; set; }
        public decimal PriceForBuy { get; set; }
        public Nullable<decimal> PriceForRent { get; set; }
    }
}
